package en

var cultureNames = map[string]string{
	"af-ZA":       "Afrikaans (South Africa)",
	"am-ET":       "Amharic (Ethiopia)",
	"ar-AE":       "Arabic (U.A.E.)",
	"ar-BH":       "Arabic (Bahrain)",
	"ar-DZ":       "Arabic (Algeria)",
	"ar-EG":       "Arabic (Egypt)",
	"ar-IQ":       "Arabic (Iraq)",
	"ar-JO":       "Arabic (Jordan)",
	"ar-KW":       "Arabic (Kuwait)",
	"ar-LB":       "Arabic (Lebanon)",
	"ar-LY":       "Arabic (Libya)",
	"ar-MA":       "Arabic (Morocco)",
	"arn-CL":      "Mapudungun (Chile)",
	"ar-OM":       "Arabic (Oman)",
	"ar-QA":       "Arabic (Qatar)",
	"ar-SA":       "Arabic (Saudi Arabia)",
	"ar-SY":       "Arabic (Syria)",
	"ar-TN":       "Arabic (Tunisia)",
	"ar-YE":       "Arabic (Yemen)",
	"as-IN":       "Assamese (India)",
	"az-Cyrl-AZ":  "Azeri (Cyrillic, Azerbaijan)",
	"az-Latn-AZ":  "Azeri (Latin, Azerbaijan)",
	"ba-RU":       "Bashkir (Russia)",
	"be-BY":       "Belarusian (Belarus)",
	"bg-BG":       "Bulgarian (Bulgaria)",
	"bn-BD":       "Bengali (Bangladesh)",
	"bn-IN":       "Bengali (India)",
	"bo-CN":       "Tibetan (PRC)",
	"br-FR":       "Breton (France)",
	"bs-Cyrl-BA":  "Bosnian (Cyrillic, Bosnia and Herzegovina)",
	"bs-Latn-BA":  "Bosnian (Latin, Bosnia and Herzegovina)",
	"ca-ES":       "Catalan (Catalan)",
	"co-FR":       "Corsican (France)",
	"cs-CZ":       "Czech (Czech Republic)",
	"cy-GB":       "Welsh (United Kingdom)",
	"da-DK":       "Danish (Denmark)",
	"de-AT":       "German (Austria)",
	"de-CH":       "German (Switzerland)",
	"de-DE":       "German (Germany)",
	"de-LI":       "German (Liechtenstein)",
	"de-LU":       "German (Luxembourg)",
	"dsb-DE":      "Lower Sorbian (Germany)",
	"dv-MV":       "Divehi (Maldives)",
	"el-GR":       "Greek (Greece)",
	"en-029":      "English (Caribbean)",
	"en-AU":       "English (Australia)",
	"en-BZ":       "English (Belize)",
	"en-CA":       "English (Canada)",
	"en-GB":       "English (United Kingdom)",
	"en-IE":       "English (Ireland)",
	"en-IN":       "English (India)",
	"en-JM":       "English (Jamaica)",
	"en-MY":       "English (Malaysia)",
	"en-NZ":       "English (New Zealand)",
	"en-PH":       "English (Republic of the Philippines)",
	"en-SG":       "English (Singapore)",
	"en-TT":       "English (Trinidad and Tobago)",
	"en-US":       "English (United States)",
	"en-ZA":       "English (South Africa)",
	"en-ZW":       "English (Zimbabwe)",
	"es-AR":       "Spanish (Argentina)",
	"es-BO":       "Spanish (Bolivia)",
	"es-CL":       "Spanish (Chile)",
	"es-CO":       "Spanish (Colombia)",
	"es-CR":       "Spanish (Costa Rica)",
	"es-DO":       "Spanish (Dominican Republic)",
	"es-EC":       "Spanish (Ecuador)",
	"es-ES":       "Spanish (Spain, International Sort)",
	"es-GT":       "Spanish (Guatemala)",
	"es-HN":       "Spanish (Honduras)",
	"es-MX":       "Spanish (Mexico)",
	"es-NI":       "Spanish (Nicaragua)",
	"es-PA":       "Spanish (Panama)",
	"es-PE":       "Spanish (Peru)",
	"es-PR":       "Spanish (Puerto Rico)",
	"es-PY":       "Spanish (Paraguay)",
	"es-SV":       "Spanish (El Salvador)",
	"es-US":       "Spanish (United States)",
	"es-UY":       "Spanish (Uruguay)",
	"es-VE":       "Spanish (Bolivarian Republic of Venezuela)",
	"et-EE":       "Estonian (Estonia)",
	"eu-ES":       "Basque (Basque)",
	"fa-IR":       "Persian",
	"fi-FI":       "Finnish (Finland)",
	"fil-PH":      "Filipino (Philippines)",
	"fo-FO":       "Faroese (Faroe Islands)",
	"fr-BE":       "French (Belgium)",
	"fr-CA":       "French (Canada)",
	"fr-CH":       "French (Switzerland)",
	"fr-FR":       "French (France)",
	"fr-LU":       "French (Luxembourg)",
	"fr-MC":       "French (Monaco)",
	"fy-NL":       "Frisian (Netherlands)",
	"ga-IE":       "Irish (Ireland)",
	"gd-GB":       "Scottish Gaelic (United Kingdom)",
	"gl-ES":       "Galician (Galician)",
	"gsw-FR":      "Alsatian (France)",
	"gu-IN":       "Gujarati (India)",
	"ha-Latn-NG":  "Hausa (Latin, Nigeria)",
	"he-IL":       "Hebrew (Israel)",
	"hi-IN":       "Hindi (India)",
	"hr-BA":       "Croatian (Latin, Bosnia and Herzegovina)",
	"hr-HR":       "Croatian (Croatia)",
	"hsb-DE":      "Upper Sorbian (Germany)",
	"hu-HU":       "Hungarian (Hungary)",
	"hy-AM":       "Armenian (Armenia)",
	"id-ID":       "Indonesian (Indonesia)",
	"ig-NG":       "Igbo (Nigeria)",
	"ii-CN":       "Yi (PRC)",
	"is-IS":       "Icelandic (Iceland)",
	"it-CH":       "Italian (Switzerland)",
	"it-IT":       "Italian (Italy)",
	"iu-Cans-CA":  "Inuktitut (Syllabics, Canada)",
	"iu-Latn-CA":  "Inuktitut (Latin, Canada)",
	"ja-JP":       "Japanese (Japan)",
	"ka-GE":       "Georgian (Georgia)",
	"kk-KZ":       "Kazakh (Kazakhstan)",
	"kl-GL":       "Greenlandic (Greenland)",
	"km-KH":       "Khmer (Cambodia)",
	"kn-IN":       "Kannada (India)",
	"kok-IN":      "Konkani (India)",
	"ko-KR":       "Korean (Korea)",
	"ky-KG":       "Kyrgyz (Kyrgyzstan)",
	"lb-LU":       "Luxembourgish (Luxembourg)",
	"lo-LA":       "Lao (Lao P.D.R.)",
	"lt-LT":       "Lithuanian (Lithuania)",
	"lv-LV":       "Latvian (Latvia)",
	"mi-NZ":       "Maori (New Zealand)",
	"mk-MK":       "Macedonian (Former Yugoslav Republic of Macedonia)",
	"ml-IN":       "Malayalam (India)",
	"mn-MN":       "Mongolian (Cyrillic, Mongolia)",
	"mn-Mong-CN":  "Mongolian (Traditional Mongolian, PRC)",
	"moh-CA":      "Mohawk (Mohawk)",
	"mr-IN":       "Marathi (India)",
	"ms-BN":       "Malay (Brunei Darussalam)",
	"ms-MY":       "Malay (Malaysia)",
	"mt-MT":       "Maltese (Malta)",
	"nb-NO":       "Norwegian, Bokmål (Norway)",
	"ne-NP":       "Nepali (Nepal)",
	"nl-BE":       "Dutch (Belgium)",
	"nl-NL":       "Dutch (Netherlands)",
	"nn-NO":       "Norwegian, Nynorsk (Norway)",
	"nso-ZA":      "Sesotho sa Leboa (South Africa)",
	"oc-FR":       "Occitan (France)",
	"or-IN":       "Oriya (India)",
	"pa-IN":       "Punjabi (India)",
	"pl-PL":       "Polish (Poland)",
	"prs-AF":      "Dari (Afghanistan)",
	"ps-AF":       "Pashto (Afghanistan)",
	"pt-BR":       "Portuguese (Brazil)",
	"pt-PT":       "Portuguese (Portugal)",
	"qut-GT":      "K'iche (Guatemala)",
	"quz-BO":      "Quechua (Bolivia)",
	"quz-EC":      "Quechua (Ecuador)",
	"quz-PE":      "Quechua (Peru)",
	"rm-CH":       "Romansh (Switzerland)",
	"ro-RO":       "Romanian (Romania)",
	"ru-RU":       "Russian (Russia)",
	"rw-RW":       "Kinyarwanda (Rwanda)",
	"sah-RU":      "Yakut (Russia)",
	"sa-IN":       "Sanskrit (India)",
	"se-FI":       "Sami, Northern (Finland)",
	"se-NO":       "Sami, Northern (Norway)",
	"se-SE":       "Sami, Northern (Sweden)",
	"si-LK":       "Sinhala (Sri Lanka)",
	"sk-SK":       "Slovak (Slovakia)",
	"sl-SI":       "Slovenian (Slovenia)",
	"sma-NO":      "Sami, Southern (Norway)",
	"sma-SE":      "Sami, Southern (Sweden)",
	"smj-NO":      "Sami, Lule (Norway)",
	"smj-SE":      "Sami, Lule (Sweden)",
	"smn-FI":      "Sami, Inari (Finland)",
	"sms-FI":      "Sami, Skolt (Finland)",
	"sq-AL":       "Albanian (Albania)",
	"sr-Cyrl-BA":  "Serbian (Cyrillic, Bosnia and Herzegovina)",
	"sr-Cyrl-CS":  "Serbian (Cyrillic, Serbia and Montenegro (Former))",
	"sr-Cyrl-ME":  "Serbian (Cyrillic, Montenegro)",
	"sr-Cyrl-RS":  "Serbian (Cyrillic, Serbia)",
	"sr-Latn-BA":  "Serbian (Latin, Bosnia and Herzegovina)",
	"sr-Latn-CS":  "Serbian (Latin, Serbia and Montenegro (Former))",
	"sr-Latn-ME":  "Serbian (Latin, Montenegro)",
	"sr-Latn-RS":  "Serbian (Latin, Serbia)",
	"sv-FI":       "Swedish (Finland)",
	"sv-SE":       "Swedish (Sweden)",
	"sw-KE":       "Kiswahili (Kenya)",
	"syr-SY":      "Syriac (Syria)",
	"ta-IN":       "Tamil (India)",
	"te-IN":       "Telugu (India)",
	"tg-Cyrl-TJ":  "Tajik (Cyrillic, Tajikistan)",
	"th-TH":       "Thai (Thailand)",
	"tk-TM":       "Turkmen (Turkmenistan)",
	"tn-ZA":       "Setswana (South Africa)",
	"tr-TR":       "Turkish (Turkey)",
	"tt-RU":       "Tatar (Russia)",
	"tzm-Latn-DZ": "Tamazight (Latin, Algeria)",
	"ug-CN":       "Uyghur (PRC)",
	"uk-UA":       "Ukrainian (Ukraine)",
	"ur-PK":       "Urdu (Islamic Republic of Pakistan)",
	"uz-Cyrl-UZ":  "Uzbek (Cyrillic, Uzbekistan)",
	"uz-Latn-UZ":  "Uzbek (Latin, Uzbekistan)",
	"vi-VN":       "Vietnamese (Vietnam)",
	"wo-SN":       "Wolof (Senegal)",
	"xh-ZA":       "isiXhosa (South Africa)",
	"yo-NG":       "Yoruba (Nigeria)",
	"zh-CN":       "Chinese (Simplified, PRC)",
	"zh-HK":       "Chinese (Traditional, Hong Kong S.A.R.)",
	"zh-MO":       "Chinese (Traditional, Macao S.A.R.)",
	"zh-SG":       "Chinese (Simplified, Singapore)",
	"zh-TW":       "Chinese (Traditional, Taiwan)",
	"zu-ZA":       "isiZulu (South Africa)",
}
